---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: text-recognition
  name: text-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      run: text-recognition
  strategy: {}
  template:
    metadata:
      labels:
        run: text-recognition
    spec:
      containers:
      - env:
        - name: Eula
          value: accept
        - name: Billing
          value: https://westus.api.cognitive.microsoft.com/vision/v2.0
        - name: ApiKey
          value: API_KEY
        image: containerpreview.azurecr.io/microsoft/cognitive-services-recognize-text:latest
        name: text-recognition
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: acrsecret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: text-recognition
  name: text-recognition
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: text-recognition
status:
  loadBalancer: {}
